### ISSUE TITLE
Error Update !!

### ISSUE THREAD

**Issue by elstringer** [gravypod/StarmadeWrapper#2]
INFOS: Installing update.
java.io.IOException: File downloaded is the incorrect size!
        at com.gravypod.wrapper.VersionManager.downloadUpdate(VersionManager.java:127)
        at com.gravypod.wrapper.server.Server.<init>(Server.java:84)
        at com.gravypod.wrapper.ServerWrapper.main(ServerWrapper.java:23)
janv. 25, 2015 6:27:16 PM com.gravypod.wrapper.StarmadeServerThread run

**Comment by gravypod** [comment]
This might be a network error. Could you try and rerun and tell me if it happens again?

**Comment by elstringer** [comment]
I try different dedicated server and the same error = /



CPU
    Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
    Coeurs : 8
    Cache : 10240KB
RAM
    4x 16384Mo
Disques
    2 x 2000 Go (raid 1)
Carte Mère
    X9SRE/X9SRE-3F/X9SRi/X9SRi-3F

and 



CPU
    IAtom™ N2800 @ 1.86GHz
    Coeurs : 4
    Cache : 1024KB
RAM
    4x 1024Mo
Disques
    1000 Go (raid 0)
Carte Mère
    X9SRE/X9SRE-3F/X9SRi/X9SRi-3F
