### ISSUE TITLE
Error !claim

### ISSUE THREAD

**Issue by elstringer** [gravypod/StarmadeWrapper#3]
java.io.IOException: Server returned HTTP response code: 403 for URL: http://starmade-servers.com/api/?object=servers&element=voters&key=pnl35nwk0bahgfpb8n0jo91bblv3t7zfdw&month=current&format=json
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
        at java.net.URL.openStream(URL.java:1037)
        at com.gravypod.claim.ClaimCommand$1.run(ClaimCommand.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by gravypod** [comment]
I have an updated version that I need to push fixing this bug. I'll be uploading it most likely later this week. I'm just testing it and trying to work out the cause of another few bugs. Sorry for the trouble and have a nice weekend.

**Comment by hunter688** [comment]
problem are cookies, which needed when make http request

**Comment by gravypod** [comment]
Yes, I have it fixedi n a private repository. I'm not really maintaining this anymore. I put it out as an example plugin. Feel free to fork it and keep it alive. Sorry, I'm just a bit busy with school and other work ATM. 

Best of luck.

**Comment by hunter688** [comment]
I make some tests, and problem is no cookies, but you must send user-agent.
